import Head from 'next/head';
import Image from 'next/image';
import Input from './Input';
import Region from './Region'
import Axios from 'axios'
import { useState, useEffect} from 'react';
import CountriesList from './CountriesList';



export default function Home() {
  const [filter, setfilter] = useState('');
  const [continents, setcontinents] = useState('');
  const [regional, setregional] = useState([]);
  const [themeChanger, setthemeChanger] = useState(false);
  const [mode, setMode ] = useState('Dark Mode')

  const searchChange = (e) => {
    setfilter(e.target.value)
  }
  const selectChange = (e) => {
    setcontinents(e.target.value)
  }
  useEffect(() => {
      Axios.get('https://restcountries.com/v2/all').then((res) => {
        setregional(res.data)
      })
  },[])


  const filteredContent = regional.filter(content => {
    return content.region.toLowerCase().includes(continents.toLowerCase()) && content.name.toLowerCase().includes(filter.toLowerCase())
  })
const toggle = () => {
  themeChanger === true ? setMode('Dark Mode') : setMode ('Light Mode')
  setthemeChanger(!themeChanger)
}
  
  return (

    <div>
      <Head>

      <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,400;1,900&display=swap" rel="stylesheet" /> 

        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <div className={` ${themeChanger && 'dark'}`}>
      <main className={`h-fit min-h-screen dark:bg-gray-800 bg-white dark:text-white w-full pb-3 transition-all`}>
        <div className=''>
          <div className={`flex items-center justify-between dark:bg-gray-700 bg-white pt-4 pb-4 px-8 dark:text-white text-black ${themeChanger && 'dark'}`}>
            <h1 className='font-bold'>Where in the world?</h1>
            <button onClick={toggle} className='cursor-pointer py-2 px-4 border'>{mode}</button>
          </div>
          <div className='pt-8 px-8 flex justify-between'>
          <Input themeChanger={themeChanger} searchChange={searchChange} searchValue={filter} />
         <Region themeChanger={themeChanger} selectChange={selectChange}/>
          </div>
          <div className='pt-10 px-8 grid grid-cols-2 gap-8 md:grid-cols-4 '>
            <CountriesList themeChanger={themeChanger} countries={filteredContent} />
          </div>
        </div>
      </main>
      </div>
      
    </div>
 
  )
}
