import Head from "next/head";
import Image from "next/image";
import Input from "./Input";
import Region from "./Region";
import Axios from "axios";
import { useState, useEffect } from "react";
import CountriesList from "./CountriesList";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [filter, setfilter] = useState("");
  const [continents, setcontinents] = useState("");
  const [regional, setregional] = useState([]);
  const [themeChanger, setthemeChanger] = useState(false);
  const [mode, setMode] = useState({
    name: "Dark Mode",
    dark: "dark_mode",
  });

  const searchChange = (e) => {
    setfilter(e.target.value);
  };
  const selectChange = (e) => {
    setcontinents(e.target.value);
  };
  useEffect(() => {
    Axios.get("https://restcountries.com/v2/all").then((res) => {
      setregional(res.data);
    });
  }, []);

  const filteredContent = regional.filter((content) => {
    return (
      content.region.toLowerCase().includes(continents.toLowerCase()) &&
      content.name.toLowerCase().includes(filter.toLowerCase())
    );
  });
  const toggle = () => {
    themeChanger === true
      ? setMode({ name: "Dark Mode", dark: "dark_mode" })
      : setMode({ name: "Light Mode", dark: "wb_sunny" });
    setthemeChanger(!themeChanger);
  };

  return (
    <div>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={` ${themeChanger && "dark"}`}>
        <main
          className={`h-fit min-h-screen dark:bg-gray-800 bg-white dark:text-white w-full pb-3 transition-all`}
        >
          <div className="">
            <div
              className={`flex items-center justify-between dark:bg-gray-700 bg-white pt-4 pb-4 px-2 dark:text-white text-black ${
                themeChanger && "dark"
              }`}
            >
              <h1 className="font-bold">Where in the world?</h1>
              <button
                onClick={toggle}
                className="cursor-pointer flex py-2 px-4 border justify-between rounded-lg"
              >
                <span className="material-symbols-outlined">{mode.dark}</span>
                {mode.name}
              </button>
            </div>
            <div className="pt-8 px-2 flex justify-between">
              <Input
                themeChanger={themeChanger}
                searchChange={searchChange}
                searchValue={filter}
              />
              <Region themeChanger={themeChanger} selectChange={selectChange} />
            </div>
            <div className="pt-10 px-2 grid grid-cols-2 gap-2 md:gap-8 md:grid-cols-4 relative">
              {regional.length === 0 ? (
                <div className={styles.spinnerContainer}>
                  <div className={styles.loadingSpinner}></div>
                </div>
              ) : (
                <CountriesList
                  themeChanger={themeChanger}
                  countries={filteredContent}
                />
              )}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
